services:
  app:
    image: atyantik/laravel-php:8.4-bullseye
    container_name: php_app
    volumes:
      - ./public:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app_network

  webserver:
    image: nginx:latest
    container_name: nginx_web
    volumes:
      - ./public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
